#!/usr/bin/env bash

dir=$(realpath $(dirname $0))
export src=$dir/src
export res=$dir/res

function install() {
    pacman -S --noconfirm "$@"
}
export -f install

if [[ ! $EUID -eq 0 ]]; then 
    echo "Script must be run as root!"
    exit
fi

user=""
user=$(ps au --noheader | cut -d " " -f 1 | sort | uniq | grep -v "root" | grep -v "admin")

while [[ $user = "" ]]; do
    echo "User not found please type username"
    read user

    if [[ ! -d /home/$user ]]; then
        echo "Invalid user"
        user=""
    fi
done

export home=/home/$user

clear
sleep 0.25s

for((i=3; i>0; i--)); do
    printf "\rWelcome $user, installing Arch config in $i"
    sleep 1s
done

echo ""

$src/xsession $user $res