- name: Update system
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install git
  apt:
    name: git
    state: present

- name: Install build lib
  apt:
    pkg: 
      - make
      - gcc
      - g++
      - libxinerama-dev
      - libxcb-xinerama0-dev
      - libxcb-util-dev
      - libxcb-icccm4-dev
      - libxcb-randr0-dev
      - libxcb-ewmh-dev
      - libxcb-keysyms1-dev
      - libxcb-shape0-dev
    state: present

# create ~/.rice/build/bspwm-rounded
- name: Create build directory
  ansible.builtin.file:
    path:  /home/timothe/.rice/build
    state: directory

# clone https://github.com/phuhl/bspwm-rounded.git
- name: Clone bspwm-rounded
  ansible.builtin.git:
    repo: https://github.com/phuhl/bspwm-rounded.git
    dest: /home/timothe/.rice/build/bspwm-rounded

# build bspwm-rounded
- name: Build bspwm-rounded
  ansible.builtin.shell: make
  args:
    chdir: /home/timothe/.rice/build/bspwm-rounded

# run make install
- name: Install bspwm-rounded
  ansible.builtin.shell: sudo make install
  args:
    chdir: /home/timothe/.rice/build/bspwm-rounded