- name: Update system
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_method: sudo

- name: Install git
  apt:
    name: git
    state: present
  become: true
  become_method: sudo

- name: Install build lib
  apt:
    pkg: 
      - make
      - gcc
      - g++
      - libxinerama-dev
      - libxcb-xinerama0-dev
      - libxcb-util-dev
      - libxcb-icccm4-dev
      - libxcb-randr0-dev
      - libxcb-ewmh-dev
      - libxcb-keysyms1-dev
      - libxcb-shape0-dev
    state: present
  become: true
  become_method: sudo

- name: Create build directory
  ansible.builtin.file:
    path:  ~/.rice/build
    state: directory

- name: Clone bspwm-rounded
  ansible.builtin.git:
    repo: https://github.com/phuhl/bspwm-rounded.git
    dest: ~/.rice/build/bspwm-rounded

- name: Build bspwm-rounded
  ansible.builtin.shell: make
  args:
    chdir: ~/.rice/build/bspwm-rounded

- name: Install bspwm-rounded
  ansible.builtin.shell: sudo make install
  args:
    chdir: ~/.rice/build/bspwm-rounded

- name: Create bspwm directory
  ansible.builtin.file:
    path: ~/.config/bspwm
    state: directory

- name: Copy bspwmrc
  ansible.builtin.copy:
    src: bspwmrc
    dest: ~/.config/bspwm/bspwmrc
    owner: timothe
    group: timothe
    mode: 0755