- name: Update system
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install git
  apt:
    name: git
    state: present

- name: Install build lib
  apt:
    name:
    state: present

# create ~/.rice/build/bspwm-rounded
- name: Create build directory
  ansible.builtin.file:
    path: ~/.rice/build
    state: directory

# clone https://github.com/phuhl/bspwm-rounded.git
- name: Clone bspwm-rounded
  ansible.builtin.git:
    repo: https://github.com/phuhl/bspwm-rounded.git
    dest: ~/.rice/build/bspwm-rounded