- name: Update system
  apt:
    update_cache: yes
    cache_valid_time: 3600

# install rust with "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
- name: Install rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# add rust to path
- name: Add rust to path
  ansible.builtin.shell: echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> /home/timothe/.bashrc

- name: Create build directory
  ansible.builtin.file:
    path:  /home/timothe/.rice/build
    state: directory

# clone eww "https://github.com/elkowar/eww.git"
- name: Clone eww
  ansible.builtin.git:
    repo: https://github.com/elkowar/eww.git
    dest: /home/timothe/.rice/build/eww

- name: Build eww
  ansible.builtin.shell: source /home/timothe/.bashrc && cargo build --release --no-default-features --features x11
  args:
    chdir: /home/timothe/.rice/build/eww

- name: Install eww
  ansible.builtin.shell: sudo cp /home/timothe/.rice/build/eww/target/release/eww /usr/local/bin

- name: Create eww directory
  ansible.builtin.file:
    path:  /home/timothe/.config/eww
    state: directory