- name: Update system
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_method: sudo

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install rust
  ansible.builtin.shell: /tmp/sh.rustup.rs -y

- name: Create build directory
  ansible.builtin.file:
    path:  ~/.rice/build
    state: directory

# clone eww "https://github.com/elkowar/eww.git"
- name: Clone eww
  ansible.builtin.git:
    repo: https://github.com/elkowar/eww.git
    dest: ~/.rice/build/eww

# install deps
- name: Install deps
  apt:
    pkg:
      - pkg-config
      - libglib2.0-dev
      - libcairo2-dev 
      - libgdk3.0-cil-dev 
      - libgdk-pixbuf2.0-dev 
      - libatk1.0-dev
      - libpango1.0-dev 
      - libgtk-3-dev
  become: true
  become_method: sudo

- name: Build eww
  ansible.builtin.shell: cargo build --release --no-default-features --features x11
  args:
    chdir: ~/.rice/build/eww
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"


- name: Install eww
  ansible.builtin.shell: cp ~/.rice/build/eww/target/release/eww ~/.local/bin/eww

# check if path contains ~/.local/bin
- name: Check if path contains ~/.local/bin
  ansible.builtin.shell: echo $PATH | grep -q ~/.local/bin
  register: path_contains_local_bin
  ignore_errors: true

# if path does not contain ~/.local/bin, add it
- name: Add ~/.local/bin to path
  ansible.builtin.shell: echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
  when: path_contains_local_bin.rc != 0

- name: Create eww directory
  ansible.builtin.file:
    path:  ~/.config/eww
    state: directory

# copy all files to ~/.config/eww
- name: Copy rofi config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/eww/
    owner: timothe
    group: timothe
    mode: 0644
  with_fileglob:
    - "{{ role_path }}/files/*"

# chmod +x each file in ~/.config/eww/script
- name: Make scripts executable
  ansible.builtin.file:
    path: ~/.config/eww/script/{{ item }}
    mode: 0755
  with_fileglob:
    - ~/.config/eww/script/*