- include_role:
    name: bspwm

- include_role:
    name: sxhkd

- include_role:
    name: picom

- include_role:
    name: eww

- name: Install rofi
  apt:
    pkg: 
      - rofi
      - dunst
      - feh
      - kitty
      - flameshot
      - firefox

    state: present
  become: true
  become_method: sudo

- include_role:
    name: feh

- include_role:
    name: rofi

- include_role:
    name: kitty