- include_role:
    name: bspwm

- include_role:
    name: sxhkd

- include_role:
    name: picom

- include_role:
    name: eww

- name: Install rofi
  apt:
    pkg: 
      - rofi
      - dunst
      - feh

    state: present
  become: true
  become_method: sudo