# create rofi config directory
- name: Create rofi directory
  ansible.builtin.file:
    path:  /home/timothe/.config/rofi
    state: directory

# copy all files to ~/.config/rofi
- name: Copy rofi config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/rofi/
    owner: timothe
    group: timothe
    mode: 0644
  with_fileglob:
    - "{{role_path}}/files/*"


