#! /bin/bash



bspc subscribe node_state | while read -r _ _ _ _ state flag; do

if [ "$state" != "fullscreen" ]; then

continue

fi

if [ "$flag" == on ]; then

$HOME/bin/eww close-all

else

$HOME/bin/eww  open bar

fi

done &
