#!/usr/bin/env bash

install lightdm lightdm-webkit2-greeter 

git clone https://github.com/paysonwallach/aqua-lightdm-webkit-theme /usr/share/lightdm-webkit/themes/aqua

rm -f /etc/lightdm/lightdm.conf 2> /dev/null
rm -f /etc/lightdm/lightdm-webkit2-greeter.conf 2> /dev/null
rm -f /usr/share/backgrounds/current 2> /dev/null

ln -s $res/lightdm/lightdm-webkit2-greeter.conf /etc/lightdm/
ln -s $res/lightdm/lightdm.conf /etc/lightdm/
ln -s $res/lightdm/background.jpg /usr/share/backgrounds/current